.PHONY: clean All

All:
	@echo "----------Building project:[ CellFilling - Debug ]----------"
	@cd "CellFilling" && "$(MAKE)" -f  "CellFilling.mk"
clean:
	@echo "----------Cleaning project:[ CellFilling - Debug ]----------"
	@cd "CellFilling" && "$(MAKE)" -f  "CellFilling.mk" clean
